# Generated by Django 3.0.4 on 2020-04-06 01:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(default=100000, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('client_name', models.CharField(max_length=20)),
                ('client_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('username', models.CharField(max_length=8, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, choices=[{'Mr.', 'Mr'}, {'Mrs', 'Mrs.'}, {'Ms', 'Ms.'}, {'Dr', 'Dr.'}], max_length=4)),
                ('firstname', models.CharField(blank=True, max_length=45, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=45, verbose_name='Middle Name')),
                ('lastname', models.CharField(blank=True, max_length=45, verbose_name='Last Name')),
                ('job_title', models.CharField(blank=True, max_length=45)),
                ('officephone', models.CharField(blank=True, max_length=12, verbose_name='Office phone')),
                ('cellphone', models.CharField(blank=True, max_length=12, verbose_name='Cell phone')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
