# Generated by Django 3.0.8 on 2020-07-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=8, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=5)),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('officephone', models.CharField(blank=True, max_length=12, verbose_name='Office phone')),
                ('cellphone', models.CharField(blank=True, max_length=12, verbose_name='Cell phone')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
