# Generated by Django 3.0.5 on 2020-04-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0002_user_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='client_id',
        ),
    ]
