# Generated by Django 3.0.5 on 2020-04-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarpv', '0003_remove_user_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='solarpv.Client'),
        ),
    ]
